services:
  game-mate-backend:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - PORT=10000
    ports:
      - "10000:10000"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: game_mate
    ports:
      - "5432:5432"