spring:
  application:
    name: game-mate-backend
  config:
    import: [
      classpath:jwt.yml,
      classpath:oauth2.yml,
      classpath:db.yml,
      classpath:socketio.yml,
    ]
server:
  port: ${SPRING_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: [ 'health' ]