spring:
  application:
    name: game-mate-backend
  config:
    import: [
      classpath:jwt.yml,
      classpath:oauth2.yml,
      classpath:db.yml,
      classpath:socketio.yml,
    ]
server:
  port: ${PORT:8080}