spring:
  datasource:
    username: ${DB_USERNAME:backend}
    password: ${DB_PASSWORD:backend}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect