spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:game_mate}
    username: ${DB_USERNAME:backend}
    password: ${DB_PASSWORD:backend}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb: debug
