spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID:Ov23li8lYCIfzIqiQr6g}
            clientSecret: ${GITHUB_CLIENT_SECRET:ca56be17fbfdf16e58271c4ba1cf678e15ab6521}
